name: list_view_pagination_tut
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_bloc: ^0.20.0
  built_value: ^6.7.0
  kiwi: ^0.2.0
  built_collection: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.6.4
  built_value_generator: ^6.7.0

 
flutter:  
  uses-material-design: true

